spring:
  application:
    name: "OrgFin-app-transacoes-api"
  cloud:
    aws:
      endpoint: "https://dynamodb.sa-east-1.amazonaws.com"
      credentials:
        access-key: ${AWS_ACCESSKEY}
        secret-key: ${AWS_SECRETKEY}
      regions:
        static: "sa-east-1"
      dynamodb:
        table-prefix: "tb_"
        table-sufix:
      cognito:
        user-pool-id: "sa-east-1_v4yhpN41u"
server:
  address: "0.0.0.0"
  port: "8080"